name: scribble
repository: https://github.com/kushalmahapatro/scribble

sdkPath: .fvm/flutter_sdk

packages:
  - packages/packages/flutter_peer2peer
  - packages/packages/peer2peer

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # # Only allow versioning to happen on main branch.
    # branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:

  generate:
    run: flutter pub global run intl_utils:generate 
      && dart run build_runner build --delete-conflicting-outputs 
    description: Generate code for a specific package in this project.

  analyze:
    exec: flutter analyze .
    description: Analyze a specific package in this project.

  check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.

  format:
    exec: dart format .
    description: Format a specific package in this project.

  dart:version:
    exec: dart --version
    description: Initialize a Rust library for the project.

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
