[package]
name = "peer2peer"
version = "0.0.1"
edition = "2021"

[lib]
name = "peer2peer"
crate-type = ["lib", "staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.4"

[dependencies]
flutter_rust_bridge = "1.82.4"
num = "0.4.1"
image = "0.24.7"
crossbeam = "0.8.2"
anyhow = "1.0.75"

# For the logger
lazy_static = "1.4.0"
log = "0.4.20"
simplelog = "0.12.1"
parking_lot = "0.12.1"

# p2p
libp2p = { version = "0.53.1" }
tokio = { version = "1.34.0"}
serde = {version = "=1.0.193"}
serde_json = "1.0.108"
once_cell = "1.18.0"
pretty_env_logger = "0.5.0"